### ISSUE TITLE
Problem with parsing a JSON file on Android

### ISSUE THREAD

**Issue by Ryumizuhi** [Bunny83/SimpleJSON#10]
Hi 
I have a problem when I try to parse a file with JSON an Android device.

The line 58 of the file below return a warning "Unsupported encoding: 'iso-8859-1,application/json'".
And the line 65 return a null value.

![creationdropdownassetbundle](https://user-images.githubusercontent.com/27427262/34814328-8339d5a8-f6ad-11e7-8b7c-39071d2f3fea.png)

The JSON file that I download with the WWW function : 
![api_bmu2](https://user-images.githubusercontent.com/27427262/34814247-3978f7e6-f6ad-11e7-8afa-7b6d729b6e27.jpg)

What can I change to make it work ?

Marie

**Comment by Bunny83** [comment]
This doesn't seem to be related to parsing the text as it looks like your text doesn't arrive with a known encoding. The response from the server seems to be "iso-8859-1" encoded which is latin-1

The best solution would be if you could make your server to return an utf8 encoded string. So you could try including an "Accept-Charset" request header and requesting utf8 encoding.

If that doesn't work you would need to use the iso-8859-1 encoding to properly translate the received bytes into a string. Something like that:

```
System.Text.Encoding iso_8859_1 = System.Text.Encoding.GetEncoding("iso-8859-1");
string text = iso_8859_1.GetString(www2.bytes);
```

Though working with utf8 would be the prefered solution.

**Comment by Ryumizuhi** [comment]
Thank,
I have just add https:// before the adresse and the request work.
