### ISSUE TITLE
Library Documentation?

### ISSUE THREAD

**Issue by chuck-sys** [Bunny83/SimpleJSON#12]
I like this simple-to-use JSON library. But is there documentation on what does what?

**Comment by david-pfx** [comment]
Dunno, but I used this:
http://wiki.unity3d.com/index.php/SimpleJSON

**Comment by chuck-sys** [comment]
I used that too, but it isn't complete. It just lists some examples.

**Comment by devingDev** [comment]
What else do you need? It has all you need afaik

**Comment by Bunny83** [comment]
Actually some time ago (when I realised Github now has a wiki for each repository) I started creating [a wiki documenation](https://github.com/Bunny83/SimpleJSON/wiki) for the framework. Almost all relevant information is in the JSONNode class description. However the Classes overview should give you an overview what classes and types also exist and what they are generally meant for. Note it's not complete yet but should cover most things you need to know.
