### ISSUE TITLE
Inheritance broken?

### ISSUE THREAD

**Issue by wvdvegt** [Bunny83/SimpleJSON#17]
Hi

I'm using simpleJSON to cache some name value pairs.

My declaration is 

`private static JSONNode names = new JSONObject();`

However when i call 

`names["id"] = "value";`

all I see is virtual methods of JSONNode being called (as if class hierarchy is broken). Not sure that is the intended behavior. I fixed it for now by:

`private static JSONObject names = new JSONObject();`

**Comment by Bunny83** [comment]
I can't reproduce this issue. I just created a private static JSONNode variable and use the same code as you. When i print out ToString(3) of that variable it correctly prints

```
{
   "id" : "value"
}

```

**Comment by wvdvegt** [comment]
I will have to look into it again. 
It worked when i replaced JSONNode by JSONObject, nu clue why it failed in the first place.

Btw i wrote a IValueConverter that allows you to use JSONNode in UWP databinding (it supports a converter parameter that supports very simple JSONPath syntax). Works quite nicely.
