### ISSUE TITLE
Current in KeyEnumerator should return string 

### ISSUE THREAD

**Issue by BSarmady** [Bunny83/SimpleJSON#21]
in 
```
public struct KeyEnumerator {
    ...
    public JSONNode Current { get { return m_Enumerator.Current.Key; } }
    ...
}
```

Type of Key is string and converting it to JSONNode modify key name and should be

`     public string Current { get { return m_Enumerator.Current.Key; } }
`

**Comment by Bunny83** [comment]
Yes, you're right ^^.  This was most likely a copy & paste error. Thanks, I've fixed it.

The Only point for the struct enumerators is to have a garbage free enumerator which isn't the case when we retrun JSONNode :)
