### ISSUE TITLE
convert JSONNode to json string?

### ISSUE THREAD

**Issue by ewwink** [Bunny83/SimpleJSON#22]
how?
and thanks

**Comment by Bunny83** [comment]
Uhm with ToString?!

The normal ToString will create compact json, the ToString overload with an int parameter creates formatted json indented with that many spaces per nesting level.

So you want to use either

`str = node.ToString();`
or
`str = node.ToString(3);`

**Comment by ewwink** [comment]
wow great, I don't need special method. 
Thanks
