### ISSUE TITLE
Move changelogs comments to CHANEGELOG file

### ISSUE THREAD

**Issue by rabilulu** [Bunny83/SimpleJSON#25]
Hi Bunny83,

I'm suggesting to move the **change comment logs** present in the topmost part of the source files to a dedicated **CHANGELOG** file.

This will help to reduce source file size also makes LICENSE text clean and visible.

Thanks,
RB.

**Comment by Bunny83** [comment]
Since I just added the Clone method to allow easy cloning of an existing node tree I moved the change log out of the file. I had already planned doing this at some point in time but hadn't have the time.
