### ISSUE TITLE
JSON not parsed

### ISSUE THREAD

**Issue by wearstudio** [Bunny83/SimpleJSON#49]
I have JSON

{"data":{"login":{"authentication":{"accessToken":"eyJhbGciOiJSUzI1"}}}}

SimpleJSON.JSON.Parse does not create child nodes. What could be the problem?

**Comment by Bunny83** [comment]
What exactly do you mean? Given your json text you should be able to access your accessToken like this:

```
JSONNode n = JSON.Parse(yourJsonText);
string accessToken = n["data"]["login"]["authentication"]["accessToken"];
```

What exacly doesn't work? How do you use it or try to access the child nodes?

**Comment by wearstudio** [comment]
Sorry, it works, I didn't understand a bit.
