### ISSUE TITLE
How to get the Key of JsonNode?

### ISSUE THREAD

**Issue by TonyChenn** [Bunny83/SimpleJSON#56]
How to get the Key of JsonNode?

**Comment by Bunny83** [comment]
A JSONNode does not have any connection to a potential parent. So only the parent may know which key may belong to which child. A JSONNode may be related to a certain key in a parent object, but could also be just at a particular index in a parent array. Even that array index association is just one way. When an element of the array is removed, the following indices would change. So there can't be a fix relationship between where in a parent a certain node may be referenced. It's literally just wrappers for a Dictionary (JSONObject) or List (JSONArray).

When you iterate through a parent with foreach, by default the enumerator enumerates over `KeyValuePair<string, JSONNode>`. Though there is an implicit conversion from `KeyValuePair<string, JSONNode>` to `JSONNode`, so it's possible to ignore the key and just iterate through the values / JSONNodes. Of course in that case you don't have the key at hand.

What exact issue do you have? Or what problem you want to solve?

**Comment by TonyChenn** [comment]
thanks for your reply, i have already solved the problem。use KeyValuePair<string, JSONNode> struct to get Key。
